### ISSUE TITLE
English Docs

### ISSUE THREAD

**Issue by rodrigorhas** [LucBerge/B4D#1]
Please, if you can describe everything in English it will be nice (I'm Brazilian) and may I help you to get this project further..

I know there's a translator haha :)

**Comment by LucBerge** [comment]
The french javadoc wasn't even done. I just added the link to the README file.

**Comment by LucBerge** [comment]
The wiki is now in [English](https://github.com/LucBerge/B4D/wiki) but the javadoc is still in French.
