### ISSUE TITLE
Installation is missing on Wiki

### ISSUE THREAD

**Issue by rodrigorhas** [LucBerge/B4D#2]
Bot installation and setup is missing on the Wiki

**Comment by LucBerge** [comment]
The v1.0 hasn't been released for the moment.

**Comment by LucBerge** [comment]
Done. If any other question regarding the installation, please write here.

**Comment by LucBerge** [comment]
Done.
- [French version](https://github.com/LucBerge/B4D/wiki/Installer)
- [English version](https://github.com/LucBerge/B4D/wiki/Install)
