### ISSUE TITLE
Almanax not working

### ISSUE THREAD

**Issue by Seres67** [LucBerge/B4D#28]
**Describe the bug**
```
fr.B4D.bot.B4DException: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://account.ankama.com/sso?from=http%3A%2F%2Fwww.krosmoz.com%2Ffr%2Falmanax%2F2021-04-01%3Fgame%3Ddofus
```
when trying to get today's almanax

**To Reproduce**
Try to get today's almanax

**Expected behavior**
Returns a list of items to get

**Comment by LucBerge** [comment]
Are you developing on the dev branch ?

**Comment by Seres67** [comment]
Well, I thought I was on the dev branch but I guess I wasn't.
Sorry for bothering you.

**Comment by Seres67** [comment]
I have a question still, is there anywhere I can download the database file? or create it myself?

**Comment by LucBerge** [comment]
Fixed [here](https://github.com/LucBerge/B4D/commit/5a009003d1b8618c8afc531ddf886cbdd0086975).
You can download the database from the [Datafus repo](https://github.com/LucBerge/Datafus).
