### ISSUE TITLE
Map change data

### ISSUE THREAD

**Issue by corentin-ballot** [LucBerge/B4D#29]
**A simple question to ask**
When changing map, is there a way to get data such as players, jobs ressources status and monsters on it ?

**Comment by LucBerge** [comment]
Maybe yes. We should be able to get these informations and B4D must use it. However, I haven't done it yet. In order to do it you'll first need a network analyzer like WireShark, identify the socket(s) received when changing the map and reverse engineering it to find the data you need.

**Comment by LucBerge** [comment]
Could you be interested in a documentation about "How to parse sockets" ?

**Comment by corentin-ballot** [comment]
I would ! I tried it alone but wasn't able to achived it yet...

**Comment by LucBerge** [comment]
Ok, I'll make a documentation about how to parse chat message sockets. It could be interesting to ask other bot developers how they did it (Flatybot...etc)

**Comment by LucBerge** [comment]
Done, check the wiki : https://github.com/LucBerge/B4D/wiki/Support-new-socket-parsing

**Comment by LucBerge** [comment]
By the way, I think that ressources locations are not in the "change map socket", same for the monsters locations

**Comment by LucBerge** [comment]
Note that the socket ids defined in the [SocketType ](https://github.com/LucBerge/B4D/blob/master/src/main/java/fr/B4D/socket/SocketType.java) class are for Dofus V2.58. The socket ids change at every update. The current Dofus version is 2.59 which means that the ids are wrong and need to be updated.

Also, the change map event is already parsed in the [ChangeMapEventParser](https://github.com/LucBerge/B4D/blob/dev/src/main/java/fr/B4D/socket/parser/ChangeMapEventParser.java) class. From what I remember, the socket is pretty small and doesn't contain usefull informations.

- The monsters informations (location, level, monsters...etc) must be in an other socket received when changing map and when a group pop.
- The resources locations must be in local files.
- The resources status (if it can be harvested or not) must be in an other socket received when changing map and when a resource pop.

To find the sockets you want to parse, I recommend you to go on a map and wait for a group/resource to pop.

**Comment by LucBerge** [comment]
When you change of map, multiple sockets are received. 
What I've seen so far for the version 2.59:
- `0x01` simple map change event (socket is empty)
- `0x6d` : Unknown (looks like a hash)
- `0x4f` : Informations about players (sure) and maybe more
