### ISSUE TITLE
VPN: I'm using a VPN for obvious reasons but it keeps telling me to check my internet connection.

### ISSUE THREAD

**Issue by Dr-Kye** [LucBerge/B4D#7]
I have everything where it should be and when I try to run the B4D java file it tells me to please check my internet connection. Any idea if there is something I could do to fix this? It doesn't create an error text file when this happens.

Thanks.

**Comment by LucBerge** [comment]
The jpcap library use networks devices to read sockets. A VPN create a new networks device that might not be compatible with the 1.0 version. See if it works with the 1.1 version (not realesed yet).

**Comment by LucBerge** [comment]
This error should not happend with the [latest version](https://github.com/LucBerge/B4D/releases/latest). You don't need a specific java version or whatever library. The [new installation](https://github.com/LucBerge/B4D/wiki/Install) is more simple.
